### ISSUE TITLE
can not upload icons zip

### ISSUE THREAD

**Issue by PoepieFloepie** [enchant97/web-portal#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

when i upload the icon zip i get a error

### Expected Behavior

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by PoepieFloepie** [comment]
can you maybe tell me what the icon docker folder is ,so i can make the folder myself and add icons manually

**Comment by enchant97** [comment]
Can you provide any logs, if there are any. I will investigate this as soon as possible.

For now you can place the icons at:

```
/app/data/plugins/core/icons/
    /png
    /svg
```

**Comment by PoepieFloepie** [comment]
need i link that plugins volume folder like /plugins in docker

i have a synology 220+
latest dsm 7.2

**Comment by PoepieFloepie** [comment]
[web-portal-2023-07-21T14-56-03.log.gz](https://github.com/enchant97/web-portal/files/12129930/web-portal-2023-07-21T14-56-03.log.gz)

**Comment by enchant97** [comment]
Thanks for the logs that will be useful for later.

Follow these steps for getting icons without the uploader:

1. mount /app/data
2. make directories inside it:
    - `plugins/core/icons/png/`
    - `plugins/core/icons/svg/`
3. place *.png files into `plugins/core/icons/png/`
4. place *.svg files into `plugins/core/icons/svg/`
5. go to the link customisation page, make a link and select and icon from the dropdown

> only mount `/app/plugins` if you use third-party plugins

**Comment by PoepieFloepie** [comment]
![2023-07-21 174419](https://github.com/enchant97/web-portal/assets/46219717/acb8ba30-1f16-43b0-bc8f-a6033477fa76)

**Comment by enchant97** [comment]
your bind for data should be `/app/data` and not `/data`.

You can remove `/plugins` (which should be `/app/plugins`) bind if you are not using third-party plugins.

**Comment by PoepieFloepie** [comment]
oke got it

**Comment by PoepieFloepie** [comment]
one more question about the icons

if i in darkmode it really hard to see the icons,in light mode it is oke
would be nice to have colored icons

**Comment by enchant97** [comment]
The best solution for that is really to pick icons that work with both themes. Or use an svg that can get it's outline color from the website styling.
