### ISSUE TITLE
(BUG) CSS Upload Does Not Work

### ISSUE THREAD

**Issue by iFixRobots** [enchant97/web-portal#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

I've noticed that uploading CSS Files does absolutely nothing. Is this known? 

### Expected Behavior

Upload CSS should reflect changes.

### Steps To Reproduce

1. Go to Settings
2. Administrator
3. System Settings 
4. Custom CSS
5. Upload CSS -> Result -> Nothing will change.

**Comment by iFixRobots** [comment]
Additionally, I checked the actually site's elements and I see no differences between uploading CSS and not.

**Comment by enchant97** [comment]
Can you check if the css file is being downloaded, by reloading the page with the sources tab open and finding `static/custom.css`. Then check if it has any content in it. If the file is empty and you have uploaded something, there is a problem.

**Comment by iFixRobots** [comment]
Yeah. There's nothing in it. See below:
![CleanShot 2023-09-29 at 14 04 40@2x](https://github.com/enchant97/web-portal/assets/16704121/a2dbd48a-03b8-4c01-b44d-1a5fb9136ab1)

**Comment by enchant97** [comment]
Ok thanks, will investigate further.

**Comment by enchant97** [comment]
@iFixRobots Just tested on a fresh install and it appears to work as expected (after uploading a css file it is applied), a green message should appear at the top of screen confirming it has been set.

If you are using a reverse proxy it may be doing some extra caching, try clearing your cache and see if it works.

**Comment by iFixRobots** [comment]
2 things: 
- The reverse proxy was caching it. For those interested on quick testing fixing: open dev tools -> long press refresh button -> Hard Refresh + Clear Cache
- Also - I think there might be some limitation on how much CSS you can introduce. I shorten it and it works immediately when testing on just directly the IP + Port. Where my long customization does not.

**Comment by enchant97** [comment]
Great to hear you have fixed it! You should be able to upload as much css as you want as long as it's no larger than 16MB (upload size limit).
