### ISSUE TITLE
Allow Password Modification For Users.

### ISSUE THREAD

**Issue by shandox** [enchant97/web-portal#144]
### Does it fit the projects scope?

- [X] This is relevant

### Why?

Is there a way to reset the Admin user password?

### Solution?

Allow Password Modification for Admin User.

**Comment by enchant97** [comment]
There is currently not anyway to change a users password. It sounds like a great and essential feature to add!

However, currently most of my projects are on pause due to me recovering from a fractured elbow as stated on my profile.

**Comment by shandox** [comment]
> There is currently not any way to change a users password. It sounds like a great and essential feature to add!
> 
> However, currently most of my projects are on pause due to me recovering from a fractured elbow as stated on my profile.

So sorry Sir!!! Totally understood and thank you for taking the time to reply under such circumstances. Godspeed with your recovery.
