### ISSUE TITLE
Which image to use?

### ISSUE THREAD

**Issue by zarevskaya** [enchant97/web-portal#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

Hello, 

Which image to use? 

ghcr.io/enchant97/web-portal:2 or ghcr.io/enchant97/web-portal:2.4.0 or latest, maybe?

Thanks :)

### Expected Behavior

I want to know the truth ^^

**Comment by enchant97** [comment]
- `latest`: Will give you the latest image whenever pulled.
- `X.X.X`: Will give you an exact version
- `X.X`: Will give you latest patch version for given major/minor
- `X`: Will give you latest major version

Choose whichever suits your requirements. Just know that between major versions there will be incompatibilities, as per semantic versioning rules.

**Comment by zarevskaya** [comment]
I meant, which one do you recommend.
Thanks. I edit my article to a fixed version. 

https://belginux.com/installer-web-portal-avec-docker/

It's a cool app! I understand how it works now. Thanks to share your work.

**Comment by enchant97** [comment]
Glad you enjoy it! I personally use `X.X` on my server, so that I don't get any unexpected errors if I have to re-deploy it at a later date.
